language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - extra-android-support
    - extra-android-m2repository
    - android-26

script:
  - ./gradlew clean testDebugUnitTest
