language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.0
    - extra-android-support
    - extra-android-m2repository
    - android-24

script:
  - ./gradlew clean testDebugUnitTest
