language: android

jdk: openjdk7

android:
  components:
    - build-tools-21.1.2
    - extra-android-support
    - extra-android-m2repository
    - android-21

script:
  - ./gradlew clean assembleDebug
